const colors = require("tailwindcss/colors");

module.exports = {
	purge: ["./src/**/*.html", "./src/**/*.vue", "./src/**/*.jsx", "./src**/*.tsx"],
	darkMode: "class", // or 'media' or 'class'
	theme: {
		extend: {
			colors: {
				transparent: "transparent",
				current: "currentColor",
				violet: colors.violet,
				black: colors.black,
				white: colors.white,
				gray: colors.gray,
				blue: colors.blue,
				indigo: colors.indigo,
				purple: colors.purple,
				warmgray: colors.warmGray,
				// truegray: colors.trueGray,
				// bluegray: colors.blueGray,
				// coolgray: colors.coolGray,
				// lightblue: colors.lightBlue,
				almostBlack: {
					100: "#d0d0d0",
					200: "#a1a1a1",
					300: "#727272",
					400: "#434343",
					500: "#141414",
					600: "#101010",
					700: "#0c0c0c",
					800: "#080808",
					900: "#040404",
				},
			},
			flex: {
				1: "1 1 0%",
				2: "2 2 0%",
				3: "3 3 0%",
				4: "4 4 0%",
				5: "5 5 0%",
			},
			height: (theme) => ({
				"10vh": "10vh",
				"20vh": "20vh",
				"30vh": "30vh",
				"40vh": "40vh",
				"50vh": "50vh",
				"60vh": "60vh",
				"70vh": "70vh",
				"80vh": "80vh",
				"90vh": "90vh",
			}),
			width: (theme) => ({
				"10vw": "10vw",
				"20vw": "20vw",
				"30vw": "30vw",
				"40vw": "40vw",
				"50vw": "50vw",
				"60vw": "60vw",
				"70vw": "70vw",
				"80vw": "80vw",
				"90vw": "90vw",
			}),
			minWidth: (theme) => ({
				"10vw": "10vw",
				"20vw": "20vw",
				"30vw": "30vw",
				"40vw": "40vw",
				"50vw": "50vw",
				"60vw": "60vw",
				"70vw": "70vw",
				"80vw": "80vw",
				"90vw": "90vw",
			}),
			opacity: {
				0: "0",
				5: "0.05",
				10: "0.1",
				20: "0.2",
				25: "0.25",
				30: "0.3",
				40: "0.4",
				50: "0.5",
				60: "0.6",
				70: "0.7",
				75: "0.75",
				80: "0.8",
				90: "0.9",
				95: "0.95",
				100: "1",
			},
			fontFamily: {
				inter: ['"Inter"', "sans-serif"],
				poppins: ['"Poppins"', "sans-serif"],
				montserrat: ['"Montserrat"', "sans-serif"],
				logo: ['"Boutiques of Merauke", sans-serif'],
			},
		},
	},
	variants: {
		extend: {
			ringColor: ["hover"],
			ringOffsetColor: ["hover"],
			ringOffsetWidth: ["hover"],
			ringOpacity: ["hover"],
			ringWidth: ["hover"],
		},
		accessibility: ["responsive", "focus-within", "focus"],
		alignContent: ["responsive"],
		alignItems: ["responsive"],
		alignSelf: ["responsive"],
		animation: ["responsive"],
		backgroundColor: ["responsive", "dark", "hover", "focus"],
		backgroundImage: ["responsive"],
		backgroundOpacity: ["responsive", "hover", "focus"],
		backgroundPosition: ["responsive"],
		backgroundRepeat: ["responsive"],
		backgroundSize: ["responsive"],
		borderColor: ["responsive", "dark", "hover", "focus"],
		borderOpacity: ["responsive", "hover", "focus"],
		borderRadius: ["responsive"],
		borderStyle: ["responsive"],
		borderWidth: ["responsive"],
		boxShadow: ["responsive", "hover", "focus"],
		boxSizing: ["responsive"],
		clear: ["responsive"],
		container: ["responsive"],
		cursor: [],
		display: ["responsive"],
		divideColor: ["responsive", "dark"],
		divideOpacity: ["responsive"],
		divideStyle: ["responsive"],
		divideWidth: ["responsive"],
		fill: ["responsive"],
		flex: ["responsive"],
		flexDirection: ["responsive"],
		fontFamily: ["responsive"],
		fontSize: ["responsive"],
		fontStyle: ["responsive"],
		fontWeight: ["responsive"],
		gap: ["responsive"],
		gradientColorStops: [],
		gridColumn: ["responsive"],
		gridColumnEnd: ["responsive"],
		gridColumnStart: ["responsive"],
		gridRow: ["responsive"],
		gridRowEnd: ["responsive"],
		gridRowStart: ["responsive"],
		gridTemplateColumns: ["responsive"],
		gridTemplateRows: ["responsive"],
		height: ["responsive"],
		justifyContent: ["responsive"],
		justifyItems: ["responsive"],
		justifySelf: ["responsive"],
		letterSpacing: ["responsive"],
		lineHeight: ["responsive"],
		listStyleType: ["responsive"],
		margin: ["responsive"],
		maxHeight: ["responsive"],
		maxWidth: ["responsive"],
		minHeight: ["responsive"],
		minWidth: ["responsive"],
		objectFit: ["responsive"],
		objectPosition: ["responsive"],
		opacity: ["focus-within", "hover", "focus"],
		overflow: ["responsive"],
		overscrollBehavior: ["responsive"],
		padding: ["responsive"],
		position: [],
		ringColor: ["responsive", "dark", "focus", "hover"],
		ringOpacity: ["responsive", "focus", "hover"],
		ringWidth: ["responsive", "focus", "hover"],
		rotate: ["responsive", "hover", "focus"],
		scale: ["responsive", "hover", "focus"],
		skew: [],
		space: [],
		textAlign: ["responsive"],
		textColor: ["responsive", "dark", "hover", "focus"],
		textDecoration: ["responsive", "hover", "focus"],
		textOpacity: ["responsive", "hover", "focus"],
		textOverflow: [],
		textTransform: ["responsive"],
		transform: ["responsive"],
		transformOrigin: ["responsive"],
		transitionDelay: ["responsive"],
		transitionDuration: ["responsive"],
		transitionProperty: ["responsive"],
		transitionTimingFunction: ["responsive"],
		verticalAlign: ["responsive"],
		visibility: ["responsive"],
		width: ["responsive"],
		wordBreak: [],
		zIndex: [],
	},
	plugins: [require("@tailwindcss/custom-forms")],
};
